# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetrack',
            name='street2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
