# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0003_auto_20160802_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetrack',
            name='zip',
            field=models.CharField(max_length=32),
        ),
    ]
