# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0005_racetrack_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racetrack',
            name='website',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
