# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 16:27
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0006_auto_20160802_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetrack',
            name='description',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
