# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0007_racetrack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetrack',
            name='main_email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='racetrack',
            name='main_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
