# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0013_auto_20160802_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('racetrack', models.ManyToManyField(to='racetracks.Racetrack')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
    ]
