# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_datetime', 'end_datetime']},
        ),
    ]
