# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 16:42
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
